import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Link from 'next/link'
import { Button } from "@/components/ui/button"

import {
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          {children}
        </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
